### ISSUE TITLE
Just Citing/Acknowledging Your Work

### ISSUE THREAD

**Issue by anonhostpi** [Spore-Community/SporeTools#1]
Gonna open then immediately close this issue. Just reaching out to let you know that my DBPF wiki cites this repository.
- wiki: https://anonhostpi.github.io/DBPF.js/docs/other/spec/

I'm avidly working on my own DBPF reader. If you see anything missing from my wiki (...or my lib), feel free let me know! I'm avidly working on them every day

I just wanted to be sure you knew I was citing your work! It's awesome seeing another Sims/Spore/DBPF Tool written in TypeScript! Also, hello from The Sims 4 community!

**Comment by VanillaCold** [comment]
I'm not sure if the Sims version of the DBPF format is the same as the Spore version at all.
When I tried using Sporemodder FX - the most modern and up-to-date Spore modding tool - on a Sims 4 package, it did not work at all. (whereas, for Spore's packages, it unpacks them just fine.)

**Comment by anonhostpi** [comment]
I suspect that S4PE/Sims4Tools's develop branch (which is what mine is heavily based on) could be adapted to read v3 instead of v2.0/v2.1

**Comment by VanillaCold** [comment]
Just checked the error again - according to the error message, Sporemodder FX fails to unpack Sims packages due to it not understanding the compression used.

I wouldn't be surprised if the Sims 4 and Spore didn't share most of their internal formats inside DBPFs, though. 
Spore relies heavily on its property lists (`.prop` files, with a TypeID of 0x00B1B104), and I couldn't find any of these in the Sims 4 packages I checked using your tool.

**Comment by anonhostpi** [comment]
> Sporemodder FX fails to unpack Sims packages due to it not understanding the compression used.

Doesn't surprise me. DBPF v2.0 has a unique way for marking compression. AFAIK, it only uses zip (I think) and refpack for recursively packed items.

> Spore relies heavily on its property lists (.prop files, with a TypeID of 0x00B1B104)

If that's the case, it should just be a matter of adding a Kaitai struct and/or a plugin for .prop files.
